name = "PhyloDistances"
uuid = "e638b194-4f2e-495a-b9ca-cc8e07bda67d"
version = "0.1.0"
authors = ["Carlos Vigil-Vásquez"]

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
NewickTree = "b0a14db8-6308-4ebc-8917-f72cd81f5094"

[compat]
AbstractTrees = "0.4.5"
NewickTree = "0.4.0"
julia = "1.12"
